version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "terraform"
    directory: "/modules/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
