# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Check Terraform Modules

on:
  pull_request:

jobs:
  check-terraform-module:
    name: Check Terraform Module
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit